config/routes.rb
NewsTube::Application.routes.draw do

  get "localsources/findvideos"
  resources :zipcodes
  resources :markets

  resources :channels

  root to: 'pages#home'
  get "home" => "pages#home"
  get "localchannels" => "pages#localchannels"
  get "localsources" => "localsources#findvideos"
  post "/loadzipdb" => "zipcodes#loadzipdb"
  get "/resetzipdb" => "zipcodes#resetzipdb"
  post "/loadchanneldb" => "channels#loadchanneldb"
  get "/resetchanneldb" => "channels#resetchanneldb"
  get "/twitter" => "pages#twitter"

end

app/models/channel.rb
class Channel < ActiveRecord::Base
	def self.import_data(csv)    
	    CSV.parse(csv) do |row|
	        Channel.create(:name => row[0], :category => row[1], :zipcode => row[2], :channelid => row[3])
	    end
	end

	def self.to_csv
    CSV.generate do |csv|
      all.each do |channel|
        csv << channel.attributes.values_at("name", "category", "zipcode", "channelid")
      end
    end
  end
end

app/controllers/channels_controller.rb
require 'net/http'
require 'csv'

class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.order(:name)
    @channel = Channel.new
    respond_to do |format|
      format.html
      format.csv { send_data @channels.to_csv }
    end
  end

  def iderror
  end

  def loadchanneldb
    Channel.import_data(params[:import_csv][:csv].read)
    
    redirect_to :action => "index"
  end

  def resetchanneldb
    Channel.delete_all
    
    redirect_to :action => "index"
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)

    uri = URI('https://www.googleapis.com/youtube/v3/channels?part=id&forUsername=' + @channel.name + '&key=AIzaSyAFxd-832oMCK_33cqsRBBoh7EdYHzV2oM')
    response = JSON.parse(Net::HTTP.get(uri))

    respond_to do |format|
      if response["items"] && response["items"].length > 0
        @channel.channelid = response["items"][0]["id"]

        if @channel.save
          format.html { redirect_to channels_url }
        else
          format.html { render action: 'new' }
          format.json { render json: @channel.errors, status: :unprocessable_entity }
        end
      else
        format.html { render action: 'iderror' }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      params.require(:channel).permit(:name, :category, :zipcode, :channelid)
    end
end

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4>Name:</h4>
    <input id="channel_name" name="channel[name]" type="text" />
  </div>
  <div class="field">
    <h4>Category:</h4>
    <select id="channel_category" name="channel[category]">
      <option value="local">Local</option>
      <option value="advocacy">Advocacy</option>
      <option value="prominent">Prominent</option>
    </select>
  </div>
  <div class="field">
    <h4>ZipCode:</h4>
    <input id="channel_zipcode" name="channel[zipcode]" type="text" />
  </div>
  <div>
    <input class='btn' style="margin-top:20px;" name="commit" type="submit" value="Create" />
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/iderror.html.erb
<br/>
<h4>No channel id found for name: <%= @channel.name %></h4>

<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<%= render 'form' %>

<h4 style="background:white;">Local</h4>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Zipcode</th>
      <th>Channelid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| 
      if channel.category == 'local' %>
      <tr>
        <td><%= channel.name %></td>
        <td><%= channel.zipcode %></td>
        <td><%= channel.channelid %></td>
        <td><%= link_to 'Show', channel %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end
    end %>
  </tbody>
</table>
<br/>

<h4 style="background:white;">Advocacy</h4>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Channelid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| 
      if channel.category == 'advocacy' %>
      <tr>
        <td><%= channel.name %></td>
        <td><%= channel.channelid %></td>
        <td><%= link_to 'Show', channel %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end
    end %>
  </tbody>
</table>
<br/>

<h4 style="background:white;">Prominent</h4>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Channelid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| 
      if channel.category == 'prominent' %>
      <tr>
        <td><%= channel.name %></td>
        <td><%= channel.channelid %></td>
        <td><%= link_to 'Show', channel %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end
    end %>
  </tbody>
</table>

<br/><br/><br/>

<%= form_for :import_csv, :url => {:action => 'loadchanneldb'}, :html => {:multipart => true} do |f| %>
  <%= f.file_field :csv %>
  <%= f.submit 'Upload CSV', :class => 'btn' %>
<%end%>

<%= link_to 'Download DB', channels_path(format: "csv") %>
<br/><br/>
<%= link_to "Delete DB", { :action => "resetchanneldb"}, :confirm => 'Are you sure?'%>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form' %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @channel.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @channel.category %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @channel.zipcode %>
</p>

<p>
  <strong>Channelid:</strong>
  <%= @channel.channelid %>
</p>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>