config/routes.rb
NewsTube::Application.routes.draw do

  get "localsources/findvideos"
  resources :zipcodes
  resources :markets

  resources :channels

  root to: 'pages#home'
  get "home" => "pages#home"
  get "localchannels" => "pages#localchannels"
  get "localsources" => "localsources#findvideos"
  post "/loadzipdb" => "zipcodes#loadzipdb"
  get "/resetzipdb" => "zipcodes#resetzipdb"
  post "/loadchanneldb" => "channels#loadchanneldb"
  get "/resetchanneldb" => "channels#resetchanneldb"
  get "/twitter" => "pages#twitter"

end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
	def self.import_data(csv)    
	    CSV.parse(csv) do |row|
	        Zipcode.create(:code => row[0], :lat => row[1], :long => row[2])
	    end
	end

	def to_rad
		self * Math::PI / 180
	end
	 
	  # http://www.movable-type.co.uk/scripts/latlong.html
	  # loc1 and loc2 are arrays of [latitude, longitude]
	def self.distance loc1, loc2
	     lat1, lon1 = loc1
	     lat2, lon2 = loc2
	     dLat = (lat2-lat1)* Math::PI / 180;
	     dLon = (lon2-lon1)* Math::PI / 180;
	     a = Math.sin(dLat/2) * Math.sin(dLat/2) +
	         Math.cos(lat1* Math::PI / 180) * Math.cos(lat2* Math::PI / 180) *
	         Math.sin(dLon/2) * Math.sin(dLon/2);
	     c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
	     d = 6371 * c; # Multiply by 6371 to get Kilometers
	end
end

app/controllers/zipcodes_controller.rb
require 'csv'

class ZipcodesController < ApplicationController
  before_action :set_zipcode, only: [:show, :edit, :update, :destroy]

  # GET /zipcodes
  # GET /zipcodes.json
  def index
    @zipcodes = Zipcode.all
  end

  # GET /zipcodes/1
  # GET /zipcodes/1.json
  def show
  end

  def loadzipdb
    Zipcode.import_data(params[:import_csv][:csv].read)
    
    redirect_to :action => "index"
  end

  def resetzipdb
    Zipcode.delete_all
    
    redirect_to :action => "index"
  end

  # GET /zipcodes/new
  def new
    @zipcode = Zipcode.new
  end

  # GET /zipcodes/1/edit
  def edit
  end

  # POST /zipcodes
  # POST /zipcodes.json
  def create
    @zipcode = Zipcode.new(zipcode_params)

    respond_to do |format|
      if @zipcode.save
        format.html { redirect_to @zipcode, notice: 'Zipcode was successfully created.' }
        format.json { render action: 'show', status: :created, location: @zipcode }
      else
        format.html { render action: 'new' }
        format.json { render json: @zipcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zipcodes/1
  # PATCH/PUT /zipcodes/1.json
  def update
    respond_to do |format|
      if @zipcode.update(zipcode_params)
        format.html { redirect_to @zipcode, notice: 'Zipcode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @zipcode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zipcodes/1
  # DELETE /zipcodes/1.json
  def destroy
    @zipcode.destroy
    respond_to do |format|
      format.html { redirect_to zipcodes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zipcode
      @zipcode = Zipcode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zipcode_params
      params.require(:zipcode).permit(:code, :lat, :long)
    end
end

app/views/zipcodes/_form.html.erb
<%= form_for(@zipcode) do |f| %>
  <% if @zipcode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zipcode.errors.count, "error") %> prohibited this zipcode from being saved:</h2>

      <ul>
      <% @zipcode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zipcodes/edit.html.erb
<h1>Editing zipcode</h1>

<%= render 'form' %>

<%= link_to 'Show', @zipcode %> |
<%= link_to 'Back', zipcodes_path %>

app/views/zipcodes/index.html.erb
<h1>Listing zipcodes</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Lat</th>
      <th>Long</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @zipcodes.each do |zipcode| %>
      <tr>
        <td><%= zipcode.code %></td>
        <td><%= zipcode.lat %></td>
        <td><%= zipcode.long %></td>
        <td><%= link_to 'Show', zipcode %></td>
        <td><%= link_to 'Edit', edit_zipcode_path(zipcode) %></td>
        <td><%= link_to 'Destroy', zipcode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zipcode', new_zipcode_path %>

<br/><br/><br/>

<%= form_for :import_csv, :url => {:action => 'loadzipdb'}, :html => {:multipart => true} do |f| %>
  <%= f.file_field :csv %>
  <%= f.submit 'Upload CSV', :class => 'btn' %>
<%end%>

<%= link_to "Delete DB", { :action => "resetzipdb"}, :confirm => 'Are you sure?'%>

app/views/zipcodes/new.html.erb
<h1>New zipcode</h1>

<%= render 'form' %>

<%= link_to 'Back', zipcodes_path %>

app/views/zipcodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @zipcode.code %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @zipcode.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @zipcode.long %>
</p>

<%= link_to 'Edit', edit_zipcode_path(@zipcode) %> |
<%= link_to 'Back', zipcodes_path %>